### ISSUE TITLE
Crashing... please halp

### ISSUE THREAD

**Issue by Arbore01** [FTBTeam/FTB-Chunks#154]
Crash log. Using latest releases.

Error says "FTB Chunks has failed to load correctly.  Java.lang.NoClassdeffoundError: me/shedaniel/autoconfig/ConfigData

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 5/25/21 4:18 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.replaymod.json:MinecraftAccessor,pl:mixin:APP:mixins.replaymod.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4940/1696377390.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.replaymod.json:MinecraftAccessor,pl:mixin:APP:mixins.replaymod.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4693/1140727816.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer,pl:mixin:APP:mixins.replaymod.json:MixinCamera,pl:mixin:APP:mixins.replaymod.json:MixinEntityRenderer,pl:mixin:APP:mixins.replaymod.json:MixinGameRenderer,pl:mixin:APP:mixins.replaymod.json:MixinShaderEntityRenderer,pl:mixin:APP:mixins.replaymod.json:Mixin_Omnidirectional_Camera,pl:mixin:APP:mixins.replaymod.json:Mixin_Omnidirectional_Rotation,pl:mixin:APP:mixins.replaymod.json:Mixin_Omnidirectional_SkipHand,pl:mixin:APP:mixins.replaymod.json:Mixin_PreserveDepthDuringHandRendering,pl:mixin:APP:mixins.replaymod.json:Mixin_Stereoscopic_Camera,pl:mixin:APP:mixins.replaymod.json:Mixin_Stereoscopic_HandRenderPass,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.replaymod.json:MinecraftAccessor,pl:mixin:APP:mixins.replaymod.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.replaymod.json:MinecraftAccessor,pl:mixin:APP:mixins.replaymod.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.23.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$462/1910492961.call(Unknown Source) [forge-1.16.5-36.1.23.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
-- MOD ftbchunks --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData
		at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51] {}
		at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_51] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
		at dev.ftb.mods.ftbchunks.client.FTBChunksClient.init(FTBChunksClient.java:139) ~[?:?] {re:classloading}
		at dev.ftb.mods.ftbchunks.FTBChunks.<init>(FTBChunks.java:140) ~[?:?] {re:classloading}
		at dev.ftb.mods.ftbchunks.forge.FTBChunksForge.<init>(FTBChunksForge.java:14) ~[?:?] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.1] {re:classloading}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3125/948692477.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3174/1003521077.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Mod File: ftb-chunks-forge-1605.3.1-build.7.jar
	Failure message: FTB Chunks (ftbchunks) has failed to load correctly
		java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData
	Mod Version: 1605.3.1-build.7
	Mod Issue URL: https://github.com/FTBTeam/FTB-Chunks/issues
	Exception message: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.ConfigData
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at dev.ftb.mods.ftbchunks.client.FTBChunksClient.init(FTBChunksClient.java:139) ~[?:?] {re:classloading}
	at dev.ftb.mods.ftbchunks.FTBChunks.<init>(FTBChunks.java:140) ~[?:?] {re:classloading}
	at dev.ftb.mods.ftbchunks.forge.FTBChunksForge.<init>(FTBChunksForge.java:14) ~[?:?] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.1] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3125/948692477.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3174/1003521077.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6541492192 bytes (6238 MB) / 13555990528 bytes (12928 MB) up to 33285996544 bytes (31744 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx31G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.23.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.23.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.23.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.23.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.23.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.23
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.23-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|NOSIGNATURE
		TConstruct-1.16.5-3.0.3.152.jar                   |Tinkers' Construct            |tconstruct                    |3.0.3.152           |CREATE_REG|NOSIGNATURE
		useful_backpacks-1.16.5-1.12.0.89.jar             |Useful Backpacks              |usefulbackpacks               |1.12.0.89           |CREATE_REG|f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		inventorysorter-1.16.1-18.1.0.jar                 |Simple Inventory Sorter       |inventorysorter               |18.1.0              |CREATE_REG|NOSIGNATURE
		Chunk+Pregen+Client-V1.16-1.0.1.jar               |Chunk Pregen Client           |pregen_client                 |NONE                |CREATE_REG|NOSIGNATURE
		ShoulderSurfing-1.16.4-2.0.3.jar                  |Shoulder Surfing              |shouldersurfing               |1.16.4-2.0.3        |CREATE_REG|NOSIGNATURE
		jei-1.16.5-7.7.0.91.jar                           |Just Enough Items             |jei                           |7.7.0.91            |CREATE_REG|NOSIGNATURE
		Craftable+Saddles+[1.16+All]-1.3.jar              |Craftable Saddles             |craftable_saddles             |1.3                 |CREATE_REG|NOSIGNATURE
		WAWLA-1.16.5-8.0.3.jar                            |WAWLA                         |wawla                         |8.0.3               |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Mantle-1.16.5-1.6.97.jar                          |Mantle                        |mantle                        |1.6.97              |CREATE_REG|NOSIGNATURE
		Waystones_1.16.5-7.5.1.jar                        |Waystones                     |waystones                     |7.5.1               |CREATE_REG|NOSIGNATURE
		TerraForged-1.16.5-0.2.10.jar                     |TerraForged                   |terraforged                   |0.2.10              |CREATE_REG|7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		gravestone-1.16.5-1.0.6.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.6        |CREATE_REG|NOSIGNATURE
		replaymod-1.16.4-forge-1.0.0-beta.jar             |Replay Mod                    |replaymod                     |2.5.1               |CREATE_REG|NOSIGNATURE
		comforts-forge-1.16.5-4.0.0.4.jar                 |Comforts                      |comforts                      |1.16.5-4.0.0.4      |CREATE_REG|NOSIGNATURE
		StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               |CREATE_REG|NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |CREATE_REG|NOSIGNATURE
		Chunk+Pregenerator-V1.16-3.0.5.jar                |Chunk Pregenerator            |chunkpregen                   |V1.16-3.0.5         |CREATE_REG|NOSIGNATURE
		structurize-0.13.174-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.174-ALPHA      |CREATE_REG|NOSIGNATURE
		u_team_core-1.16.5-3.2.1.195.jar                  |U Team Core                   |uteamcore                     |3.2.1.195           |CREATE_REG|f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		minecolonies-0.14.181-ALPHA-universal.jar         |MineColonies                  |minecolonies                  |0.14.181-ALPHA      |CREATE_REG|NOSIGNATURE
		architectury-1.14.156-forge.jar                   |Architectury                  |architectury                  |1.14.156            |CREATE_REG|NOSIGNATURE
		ftb-library-forge-1605.3.1-build.6.jar            |FTB Library                   |ftblibrary                    |1605.3.1-build.6    |CREATE_REG|NOSIGNATURE
		smallships-1.16.5-1.8.4.jar                       |Small Ships Mod               |smallships                    |1.8.4               |CREATE_REG|NOSIGNATURE
		ftb-teams-1605.2.0-build.56-forge.jar             |FTB Teams                     |ftbteams                      |1605.2.0-build.56   |CREATE_REG|NOSIGNATURE
		ftb-chunks-forge-1605.3.1-build.7.jar             |FTB Chunks                    |ftbchunks                     |1605.3.1-build.7    |ERROR     |NOSIGNATURE
		forge-1.16.5-36.1.23-universal.jar                |Forge                         |forge                         |36.1.23             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |CREATE_REG|NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |CREATE_REG|NOSIGNATURE
	Crash Report UUID: d45ac545-0cec-4580-87dd-112fb14f3045
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 35
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 466.47
	OpenGlRenderer: NVIDIA GeForce RTX 2080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by LatvianModder** [comment]
Install Cloth Config mod, I will fix missing dep
