### ISSUE TITLE
Crash(Exit code -1) upon installing and using Sodium-forge

### ISSUE THREAD

**Issue by FatalRex** [FTBTeam/FTB-Chunks#187]
Hello, I am using my own modpack and all mods are from curse-forge, except sodium, it is the only external mod.
I have 150 mods and am trying to keep it as light as possible.
I am using the most recent forge for MC 1.16.5 ( forge 36.2.2 ) and all mods are up to date.

I had been using optifine until I got sick of seeing 5-20 FPS. So I went with sodium.
Now I get 130 FPS with all settings on high, it's great. But.. For some reason it is crashing with FTB chunks.

Here's the report : 
[crash-2021-08-31_04.50.05-client.txt](https://github.com/FTBTeam/FTB-Chunks/files/7084860/crash-2021-08-31_04.50.05-client.txt)

Here's the snipit that mattered to me in case you just want to see the error info : 

Time: 8/31/21 4:50 AM
Description: Unexpected error

java.lang.NoClassDefFoundError: com/feed_the_beast/mods/ftbchunks/client/FTBChunksClient
at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkAdded(SodiumWorldRenderer.java:342) ~[?:2.1] {re:mixin,re:classloading}
at me.jellysquid.mods.sodium.client.world.SodiumChunkManager.onChunkLoaded(SodiumChunkManager.java:198) ~[?:2.1] {re:mixin,re:classloading}
at me.jellysquid.mods.sodium.client.world.SodiumChunkManager.func_228313_a_(SodiumChunkManager.java:125) ~[?:2.1] {re:mixin,re:classloading}
at net.minecraft.client.network.play.ClientPlayNetHandler.func_147263_a(ClientPlayNetHandler.java:726) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:ftbchunks-common.mixins.json:ClientPacketListenerMixin,pl:mixin:APP:valhelsia_core.mixins.json:client.ClientPlayNetHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}

This crash happens on world load or creation, can't get past it. Had to go with a crappy claim mod that gives no info or graphical representation on a minimap and it's painful heheh.

Thanks for a great mod that i've been enjoying for around a decade!

Cheers.

**Comment by MaxNeedsSnacks** [comment]
Sodium-Forge relies on a heavily outdated version of FTB Chunks, please report this to them instead.
