### ISSUE TITLE
Pneumaticraft Drone Fake Player Issue

### ISSUE THREAD

**Issue by JonathanCSmith** [FTBTeam/FTB-Chunks#57]
On our server we created a Pneumaticraft Drone Tree farm in an area with claimed chunks. When the drone tried to fell a tree the server crashed. With the following error:

```
[Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Illegal char <:> at index 245: 2efb5ca926454eeb80dcc568e85dda98-TextComponent{text='Pikatikaa', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}_drone.json
        Index: 10
        Listeners:
                0: HIGHEST
                1: net.minecraftforge.eventbus.EventBus$$Lambda$2737/888247784@3ad80f42
                2: NORMAL
                3: ASM: class me.desht.pneumaticcraft.common.item.ItemGPSAreaTool$EventHandler onBlockLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
                4: ASM: class me.desht.pneumaticcraft.common.item.ItemMemoryStick$Listener onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
                5: ASM: class me.desht.pneumaticcraft.common.item.ItemJackHammer$Listener onLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
                6: ASM: class com.github.alexthe666.rats.server.events.CommonEvents onPlayerLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
                7: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
                8: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler leftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
                9: net.minecraftforge.eventbus.EventBus$$Lambda$2737/888247784@65e3375a
                10: ASM: com.feed_the_beast.mods.ftbchunks.FTBChunks@62aa78cd blockLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
                11: ASM: stepsword.mahoutsukai.handlers.ServerHandler@6e226192 leftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
                12: net.minecraftforge.eventbus.EventBus$$Lambda$2737/888247784@606e7fe7
                13: net.minecraftforge.eventbus.EventBus$$Lambda$2737/888247784@49bfeff1
                14: ASM: class sonar.fluxnetworks.register.CommonEventHandler onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
                15: ASM: mod.chiselsandbits.events.EventPlayerInteract@12a965e8 interaction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
                16: net.minecraftforge.eventbus.EventBus$$Lambda$2737/888247784@33e74b9b
                17: ASM: de.maxhenkel.camera.ServerEvents@6c811d98 onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
                18: ASM: com.lothrazar.cyclic.event.ItemEvents@436622a onHit(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
                19: ASM: mcjty.lib.setup.ModSetup$EventHandler@55f74048 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
                20: ASM: me.desht.pneumaticcraft.common.event.EventHandlerPneumaticCraft@2009b75d onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
                21: ASM: me.desht.pneumaticcraft.common.event.EventHandlerUniversalSensor@3669dcb7 onInteraction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
                22: ASM: class cofh.ensorcellation.event.CommonEvents handlePlayerRightClickEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
                23: ASM: class com.stal111.forbidden_arcanus.event.PlayerInteractListener onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
                24: ASM: appeng.parts.PartPlacement@684e90a6 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
                25: ASM: mcjty.rftoolsutility.setup.ForgeEventHandlers@d70ad8d onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
                26: LOWEST
                27: net.minecraftforge.eventbus.EventBus$$Lambda$2737/888247784@4fc2f35a
java.nio.file.InvalidPathException: Illegal char <:> at index 245: 2efb5ca926454eeb80dcc568e85dda98-TextComponent{text='Pikatikaa', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}_drone.json
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at sun.nio.fs.AbstractPath.resolve(Unknown Source)
        at com.feed_the_beast.mods.ftbchunks.impl.ClaimedChunkManagerImpl.getData(ClaimedChunkManagerImpl.java:273)
        at com.feed_the_beast.mods.ftbchunks.impl.ClaimedChunkManagerImpl.getData(ClaimedChunkManagerImpl.java:285)
        at com.feed_the_beast.mods.ftbchunks.impl.ClaimedChunkPlayerDataImpl.canUse(ClaimedChunkPlayerDataImpl.java:404)
        at com.feed_the_beast.mods.ftbchunks.impl.ClaimedChunkImpl.canEdit(ClaimedChunkImpl.java:84)
        at com.feed_the_beast.mods.ftbchunks.FTBChunks.blockLeftClick(FTBChunks.java:226)
        at net.minecraftforge.eventbus.ASMEventHandler_928_FTBChunks_blockLeftClick_LeftClickBlock.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
        at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:781)
        at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:130)
        at me.desht.pneumaticcraft.common.ai.DroneAIDig.doBlockInteraction(DroneAIDig.java:101)
        at me.desht.pneumaticcraft.common.ai.DroneAIBlockInteraction.func_75253_b(DroneAIBlockInteraction.java:192)
        at me.desht.pneumaticcraft.common.ai.DroneAIManager.canContinue(DroneAIManager.java:438)
        at me.desht.pneumaticcraft.common.ai.DroneAIManager.onUpdateTasks(DroneAIManager.java:373)
        at me.desht.pneumaticcraft.common.entity.living.EntityDrone.func_70071_h_(EntityDrone.java:480)
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
        at net.minecraft.world.World.func_217390_a(World.java:554)
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
        at java.lang.Thread.run(Unknown Source)

[15:39:37] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID fe910d25-b600-4f22-915f-642d4a708d61
[15:39:37] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 245: 2efb5ca926454eeb80dcc568e85dda98-TextComponent{text='Pikatikaa', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}_drone.json
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[?:1.8.0_271] {}
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:1.8.0_271] {}
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:1.8.0_271] {}
        at sun.nio.fs.WindowsPath.parse(Unknown Source) ~[?:1.8.0_271] {}
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[?:1.8.0_271] {}
        at sun.nio.fs.AbstractPath.resolve(Unknown Source) ~[?:1.8.0_271] {}
        at com.feed_the_beast.mods.ftbchunks.impl.ClaimedChunkManagerImpl.getData(ClaimedChunkManagerImpl.java:273) ~[ftbchunks:1603.2.0.44] {re:classloading}
        at com.feed_the_beast.mods.ftbchunks.impl.ClaimedChunkManagerImpl.getData(ClaimedChunkManagerImpl.java:285) ~[ftbchunks:1603.2.0.44] {re:classloading}
        at com.feed_the_beast.mods.ftbchunks.impl.ClaimedChunkPlayerDataImpl.canUse(ClaimedChunkPlayerDataImpl.java:404) ~[ftbchunks:1603.2.0.44] {re:classloading}
        at com.feed_the_beast.mods.ftbchunks.impl.ClaimedChunkImpl.canEdit(ClaimedChunkImpl.java:84) ~[ftbchunks:1603.2.0.44] {re:classloading}
        at com.feed_the_beast.mods.ftbchunks.FTBChunks.blockLeftClick(FTBChunks.java:226) ~[ftbchunks:1603.2.0.44] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_928_FTBChunks_blockLeftClick_LeftClickBlock.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
        at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:781) ~[forge:?] {re:classloading}
        at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:130) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs.mixins.json:PlayerInteractionManagerMixin,pl:mixin:A}
        at me.desht.pneumaticcraft.common.ai.DroneAIDig.doBlockInteraction(DroneAIDig.java:101) ~[pneumaticcraft:1.16.4-2.6.2-73] {re:classloading}
        at me.desht.pneumaticcraft.common.ai.DroneAIBlockInteraction.func_75253_b(DroneAIBlockInteraction.java:192) ~[pneumaticcraft:1.16.4-2.6.2-73] {re:classloading}
        at me.desht.pneumaticcraft.common.ai.DroneAIManager.canContinue(DroneAIManager.java:438) ~[pneumaticcraft:1.16.4-2.6.2-73] {re:classloading}
        at me.desht.pneumaticcraft.common.ai.DroneAIManager.onUpdateTasks(DroneAIManager.java:373) ~[pneumaticcraft:1.16.4-2.6.2-73] {re:classloading}
        at me.desht.pneumaticcraft.common.entity.living.EntityDrone.func_70071_h_(EntityDrone.java:480) ~[pneumaticcraft:1.16.4-2.6.2-73] {re:classloading}
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:immersiveengineering:IE block update callback,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:immersiveengineering:IE block update callback,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        ... 5 mor
```

Upon rebooting we could no longer click the 'allies' button to add the fake player and the server log is filled with text about unexpected packet lengths. I missed the specific logs here but on looking through the known fake players it appears that an entire 'TextComponent' object was captured as a part of the player name. 

For now I have edited the fake player name manually in the file which restores the functionality of the allies button and unclaimed/protected the chuncks in question.

**Comment by NillerMedDild** [comment]
This is still an issue with `ftb-chunks-1604.2.2.54`, fyi.

**Comment by Sixmax** [comment]
What File did you change? We are having the same issue.

**Comment by MaxNeedsSnacks** [comment]
Fixed by Pneumaticraft
