### ISSUE TITLE
Cannot open GUI on local server

### ISSUE THREAD

**Issue by TheColeIndustry** [FTBTeam/FTB-Chunks#79]
I tried to run a Life in the Village 2 server on my machine and have repeatedly crashed as soon as I press "m" to open the GUI. This does not occur on my single player games. 

Minecraft Version: 1.15.2
FTB-Chunks Version: 1.1.1.17

At one point I accidentally copied the ftbchunks folders from my local world into the server folders and that would let me open the GUI, but it would not update and would be blank.

UPDATE: I have just managed to open the GUI, but it still will not update and the image shown for claiming chunks is from my single player game.

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 12/29/20 11:16 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.feed_the_beast.mods.ftbchunks.client.LargeMapScreen.alignWidgets(LargeMapScreen.java:175) ~[?:1.1.1.17] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.widget.Panel.refreshWidgets(Panel.java:98) ~[?:1.0.0.14] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.widget.GuiBase.initGui(GuiBase.java:91) ~[?:1.0.0.14] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.widget.GuiWrapper.init(GuiWrapper.java:34) ~[?:1.0.0.14] {re:classloading}
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:339) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:800) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at com.feed_the_beast.mods.ftbguilibrary.widget.GuiBase.openGui(GuiBase.java:393) ~[?:1.0.0.14] {re:classloading}
	at com.feed_the_beast.mods.ftbchunks.client.FTBChunksClient.openGui(FTBChunksClient.java:105) ~[?:1.1.1.17] {re:classloading}
	at com.feed_the_beast.mods.ftbchunks.client.FTBChunksClient.keyEvent(FTBChunksClient.java:235) ~[?:1.1.1.17] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_616_FTBChunksClient_keyEvent_KeyInputEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.1-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.fireKeyInput(ForgeHooksClient.java:798) ~[?:?] {re:classloading}
	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:364) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches KeyboardListener Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener.lambda$null$7(KeyboardListener.java:399) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches KeyboardListener Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener$$Lambda$13107/1445947111.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.KeyboardListener.lambda$setupCallbacks$8(KeyboardListener.java:398) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches KeyboardListener Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener$$Lambda$2025/1998511629.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:296) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:946) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.46.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$463/1632141948.call(Unknown Source) [forge-1.15.2-31.2.46.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.feed_the_beast.mods.ftbchunks.client.LargeMapScreen.alignWidgets(LargeMapScreen.java:175)
	at com.feed_the_beast.mods.ftbguilibrary.widget.Panel.refreshWidgets(Panel.java:98)
	at com.feed_the_beast.mods.ftbguilibrary.widget.GuiBase.initGui(GuiBase.java:91)
	at com.feed_the_beast.mods.ftbguilibrary.widget.GuiWrapper.init(GuiWrapper.java:34)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:339)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:800)
	at com.feed_the_beast.mods.ftbguilibrary.widget.GuiBase.openGui(GuiBase.java:393)
	at com.feed_the_beast.mods.ftbchunks.client.FTBChunksClient.openGui(FTBChunksClient.java:105)
	at com.feed_the_beast.mods.ftbchunks.client.FTBChunksClient.keyEvent(FTBChunksClient.java:235)
	at net.minecraftforge.eventbus.ASMEventHandler_616_FTBChunksClient_keyEvent_KeyInputEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.client.ForgeHooksClient.fireKeyInput(ForgeHooksClient.java:798)
	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:364)
	at net.minecraft.client.KeyboardListener.lambda$null$7(KeyboardListener.java:399)
	at net.minecraft.client.KeyboardListener$$Lambda$13107/1445947111.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.KeyboardListener.lambda$setupCallbacks$8(KeyboardListener.java:398)
	at net.minecraft.client.KeyboardListener$$Lambda$2025/1998511629.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98)

**Comment by MaxNeedsSnacks** [comment]
Should no longer be an issue, feel free to reopen if it still is
